import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRef, useState } from 'react';

import { listReports, postChat } from '@/api/ai';
import { describeApiFailure } from '@/api/client';
import { EmptyState } from '@/components/states/EmptyState';
import { ErrorState } from '@/components/states/ErrorState';
import { UnavailableState } from '@/components/states/UnavailableState';
import { Button } from '@/components/ui/Button';
import { AI_CHAT_QUESTION_MAX } from '@/lib/constants';

import { AI_CHAT_HISTORY_QUERY_KEY, AI_REPORTS_QUERY_KEY } from '../shared';

import type { ChatAnswer } from '@/types/api';

/**
 * The AI Chat page (Phase 12, ARCHITECTURE.md §7): a plain-text financial Q&A thread. Every answer
 * is grounded by the server in the user's own aggregates (R-I1) and validated before it arrives
 * (R-I4); the question is length-capped here and injection-wrapped on the server (R-I3). Nothing is
 * ever rendered as HTML — answers land only in React text nodes, which escape them (R-I5) — and the
 * page does no financial math (R-B3). The "informational, not advice" footer rides under the thread
 * so it cannot be missed (R-I5). Prior exchanges load from `GET /ai/reports?type=QA`.
 */

/** General starter questions, grounded in the aggregates the Q&A context actually carries (§5). */
const SUGGESTED_QUESTIONS = [
  'How much did I spend this month?',
  'How does this month compare with last month?',
  'Which categories am I spending the most on?',
  'Am I on track with my savings goals?',
  'Where could I cut back to save more?',
] as const;

/** One exchange in the thread: what was asked and, once it arrives, the answer. */
interface Turn {
  id: string;
  question: string;
  answer: string;
}

function record(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null ? (value as Record<string, unknown>) : {};
}

function asString(value: unknown): string {
  return typeof value === 'string' ? value : '';
}

/** The standing footer (R-I5): mirrors the server disclaimer without importing server code (R-N7). */
const ADVICE_FOOTER =
  'Answers are generated by AI from your own aggregated figures, for information only — not ' +
  'financial, tax, or investment advice. Verify figures and consult a professional before deciding.';

/** Map a chat failure to the right state: NO_DATA is empty, quota/AI-down are degraded, rest error. */
function ChatFailure({
  failure,
  onRetry,
}: {
  failure: { code: string; message: string };
  onRetry: () => void;
}) {
  if (failure.code === 'NO_DATA') {
    return <EmptyState title="Not enough data yet" message={failure.message} />;
  }
  if (failure.code === 'RATE_LIMITED') {
    return <UnavailableState title="AI limit reached" message={failure.message} />;
  }
  if (failure.code === 'AI_UNAVAILABLE' || failure.code === 'UPSTREAM_UNAVAILABLE') {
    return (
      <UnavailableState title="AI is unavailable right now" message={failure.message} onRetry={onRetry} />
    );
  }
  return <ErrorState title="Could not answer that" message={failure.message} onRetry={onRetry} />;
}

/** One exchange: the question, then the answer (or a thinking placeholder while it is in flight). */
function ThreadTurn({ turn, pending }: { turn: Turn; pending?: boolean }) {
  return (
    <div className="space-y-3">
      <div className="flex justify-end">
        <p className="max-w-[85%] whitespace-pre-wrap rounded bg-ink px-4 py-2 text-sm text-paper">
          {turn.question}
        </p>
      </div>
      <div className="flex justify-start">
        {pending ? (
          <p className="max-w-[85%] rounded border border-line px-4 py-2 text-sm text-muted">
            Thinking…
          </p>
        ) : (
          <p className="max-w-[85%] whitespace-pre-wrap rounded border border-line px-4 py-2 text-sm leading-6 text-ink-soft">
            {turn.answer}
          </p>
        )}
      </div>
    </div>
  );
}

export function ChatPage() {
  const queryClient = useQueryClient();
  const [draft, setDraft] = useState('');
  const [pendingQuestion, setPendingQuestion] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const history = useQuery({
    queryKey: AI_CHAT_HISTORY_QUERY_KEY,
    queryFn: ({ signal }) => listReports({ type: 'QA', limit: 50 }, signal),
  });

  const mutation = useMutation({
    mutationFn: (question: string) => postChat(question),
    onSuccess: (_answer: ChatAnswer) => {
      void queryClient.invalidateQueries({ queryKey: AI_CHAT_HISTORY_QUERY_KEY });
      void queryClient.invalidateQueries({ queryKey: AI_REPORTS_QUERY_KEY });
    },
    onSettled: () => {
      setPendingQuestion(null);
    },
  });

  // History arrives newest-first; the thread reads oldest-first like a conversation.
  const turns: Turn[] = [...(history.data ?? [])]
    .reverse()
    .map((report) => {
      const content = record(report.content);
      return { id: report.id, question: asString(content.question), answer: asString(content.answer) };
    })
    .filter((turn) => turn.question.length > 0);

  const failure = mutation.isError ? describeApiFailure(mutation.error) : null;
  const trimmed = draft.trim();
  const canSend = trimmed.length > 0 && trimmed.length <= AI_CHAT_QUESTION_MAX && !mutation.isPending;

  function ask(question: string) {
    const value = question.trim();
    if (value.length === 0 || value.length > AI_CHAT_QUESTION_MAX || mutation.isPending) return;
    setPendingQuestion(value);
    setDraft('');
    mutation.mutate(value);
    inputRef.current?.focus();
  }

  const showThread = turns.length > 0 || pendingQuestion !== null;
  const showSuggestions = !showThread && !history.isPending;

  return (
    <div className="mx-auto flex max-w-3xl flex-col space-y-8">
      <header>
        <h1 className="font-serif text-3xl sm:text-4xl">AI Chat</h1>
        <p className="mt-2 max-w-[60ch] text-sm text-muted">
          Ask about your own finances. Answers are drawn only from your aggregated figures —
          informational, not financial advice.
        </p>
      </header>

      {history.isError && (
        <ErrorState
          title="Could not load your conversation"
          message={describeApiFailure(history.error).message}
          retrying={history.isFetching}
          onRetry={() => {
            void history.refetch();
          }}
        />
      )}

      {showThread && (
        <div
          role="log"
          aria-live="polite"
          aria-label="Conversation"
          className="space-y-6"
        >
          {turns.map((turn) => (
            <ThreadTurn key={turn.id} turn={turn} />
          ))}
          {pendingQuestion !== null && (
            <ThreadTurn turn={{ id: 'pending', question: pendingQuestion, answer: '' }} pending />
          )}
        </div>
      )}

      {!showThread && !history.isError && !history.isPending && (
        <EmptyState
          title="Ask your first question"
          message="Pick a suggestion below or type your own. Answers use only your aggregated figures."
        />
      )}

      {showSuggestions && (
        <section aria-labelledby="suggested-heading" className="space-y-3">
          <h2 id="suggested-heading" className="text-sm font-medium">
            Try asking
          </h2>
          <ul className="flex flex-wrap gap-2">
            {SUGGESTED_QUESTIONS.map((question) => (
              <li key={question}>
                <Button
                  variant="quiet"
                  size="sm"
                  onClick={() => {
                    ask(question);
                  }}
                  disabled={mutation.isPending}
                >
                  {question}
                </Button>
              </li>
            ))}
          </ul>
        </section>
      )}

      {failure !== null && !mutation.isPending && (
        <ChatFailure
          failure={failure}
          onRetry={() => {
            if (pendingQuestion !== null) ask(pendingQuestion);
          }}
        />
      )}

      <form
        className="space-y-2"
        onSubmit={(event) => {
          event.preventDefault();
          ask(draft);
        }}
      >
        <label htmlFor="chat-question" className="sr-only">
          Your question
        </label>
        <div className="flex items-center gap-3 border-b border-line py-2.5 focus-within:border-ink">
          <input
            id="chat-question"
            ref={inputRef}
            value={draft}
            maxLength={AI_CHAT_QUESTION_MAX}
            autoComplete="off"
            placeholder="Ask about your finances…"
            onChange={(event) => {
              setDraft(event.target.value);
            }}
            className="min-w-0 flex-1 bg-transparent text-ink placeholder:text-muted"
          />
          <Button type="submit" variant="primary" size="sm" disabled={!canSend}>
            {mutation.isPending ? 'Asking…' : 'Ask'}
          </Button>
        </div>
        <p className="text-right text-xs text-muted">
          {trimmed.length}/{AI_CHAT_QUESTION_MAX}
        </p>
      </form>

      <p className="border-t border-line pt-4 text-xs leading-5 text-muted">{ADVICE_FOOTER}</p>
    </div>
  );
}
